name: flight_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  carousel_slider: ^5.0.0
  change_case: ^2.1.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.3.0
  flutter_markdown: ^0.7.4
  flutter_sticky_header: ^0.7.0
  flutter_svg: ^2.0.17
  flutter_svg_provider: ^1.0.7
  flutter_timer_countdown: ^1.0.7
  font_awesome_flutter: ^10.7.0
  form_builder_validators: ^11.0.0
  get: ^4.6.6
  intl: ^0.19.0
  overlay_tooltip: ^0.2.3
  photo_view: ^0.15.0
  pinput: ^5.0.0
  scroll_to_hide: ^2.1.0
  shared_preferences: ^2.3.2
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  zoom_tap_animation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/intro/
    - assets/images/empty/
    - assets/images/logos/
    - assets/fonts/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 700